<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVywyvyt\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVywyvyt/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVywyvyt.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVywyvyt\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVywyvyt\appDevDebugProjectContainer([
    'container.build_hash' => 'Vywyvyt',
    'container.build_id' => '99e93b02',
    'container.build_time' => 1683492611,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVywyvyt');
